Repository costcook-team/costcook-backend, pull requests merged in 2024-10, with the labels that each got.

#4 Feat: 사용자 관련 엔티티 구현
  .gitignore
  costcook/src/main/java/com/costcook/CostcookApplication.java
  costcook/src/main/java/com/costcook/domain/PlatformTypeEnum.java
  costcook/src/main/java/com/costcook/domain/RoleEnum.java
  costcook/src/main/java/com/costcook/domain/StatusEnum.java
  costcook/src/main/java/com/costcook/entity/Recipe.java
  costcook/src/main/java/com/costcook/entity/SocialAccount.java
  costcook/src/main/java/com/costcook/entity/User.java
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
Labels: 기능 추가, 백엔드

#5 Feat: 인증코드 이메일 발송 API 구현
  costcook/build.gradle
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
  costcook/src/main/java/com/costcook/controller/AuthController.java
  costcook/src/main/java/com/costcook/domain/request/EmailRequest.java
  costcook/src/main/java/com/costcook/entity/EmailVerification.java
  costcook/src/main/java/com/costcook/repository/EmailVerificationRepository.java
  costcook/src/main/java/com/costcook/service/EmailService.java
  costcook/src/main/java/com/costcook/service/impl/EmailServiceImpl.java
  costcook/src/main/java/com/costcook/util/EmailUtil.java
Labels: 기능 추가

#6 Feat: 인증 코드 확인 기능 구현
  costcook/src/main/java/com/costcook/controller/AuthController.java
  costcook/src/main/java/com/costcook/domain/request/VerificationRequest.java
  costcook/src/main/java/com/costcook/domain/response/VerifyCodeResponse.java
  costcook/src/main/java/com/costcook/exceptions/ErrorResponse.java
  costcook/src/main/java/com/costcook/exceptions/GlobalExceptionHandler.java
  costcook/src/main/java/com/costcook/repository/EmailVerificationRepository.java
  costcook/src/main/java/com/costcook/service/EmailService.java
  costcook/src/main/java/com/costcook/service/impl/EmailServiceImpl.java
Labels: 기능 추가, 리팩토링, 백엔드

#9 Feat: 구글/카카오 로그인 시 필요한 API 구현
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
  costcook/src/main/java/com/costcook/controller/AuthController.java
  costcook/src/main/java/com/costcook/controller/OAuthController.java
  costcook/src/main/java/com/costcook/domain/OAuthUserInfo.java
  costcook/src/main/java/com/costcook/domain/PlatformTypeEnum.java
  costcook/src/main/java/com/costcook/domain/request/SignUpOrLoginRequest.java
  costcook/src/main/java/com/costcook/domain/response/SignUpOrLoginResponse.java
  costcook/src/main/java/com/costcook/entity/SocialAccount.java
  costcook/src/main/java/com/costcook/entity/User.java
  costcook/src/main/java/com/costcook/exceptions/InvalidProviderException.java
  costcook/src/main/java/com/costcook/exceptions/MissingFieldException.java
  costcook/src/main/java/com/costcook/repository/SocialAccountRepository.java
  costcook/src/main/java/com/costcook/repository/UserRepository.java
  costcook/src/main/java/com/costcook/security/JwtProperties.java
  costcook/src/main/java/com/costcook/security/JwtProvider.java
  costcook/src/main/java/com/costcook/service/AuthService.java
  costcook/src/main/java/com/costcook/service/UserService.java
  costcook/src/main/java/com/costcook/service/impl/AuthServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/UserServiceImpl.java
  costcook/src/main/java/com/costcook/util/OAuth2Properties.java
  costcook/src/main/java/com/costcook/util/TokenUtils.java
Labels: 기능 추가, 리팩토링, 백엔드

#11 Feat: 액세스 토큰 재발급 API 구현
  costcook/src/main/java/com/costcook/controller/AuthController.java
  costcook/src/main/java/com/costcook/service/AuthService.java
  costcook/src/main/java/com/costcook/service/impl/AuthServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/UserDetailsServiceImpl.java
Labels: 기능 추가, 백엔드

#14 Feat: 내 정보 조회 API 구현 및 JwtAuthenticationFilter 구현, 적용
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
  costcook/src/main/java/com/costcook/controller/UserController.java
  costcook/src/main/java/com/costcook/domain/response/UserResponse.java
  costcook/src/main/java/com/costcook/security/JwtAuthenticationFilter.java
  costcook/src/main/java/com/costcook/util/TokenUtils.java
  costcook/src/main/resources/application.yml
Labels: 기능 추가, 백엔드

#18 Feat; 재료, 카테고리, 단위 엔티티 생성
  costcook/src/main/java/com/costcook/entity/Category.java
  costcook/src/main/java/com/costcook/entity/Ingredient.java
  costcook/src/main/java/com/costcook/entity/Unit.java
Labels: 기능 추가, 백엔드

#17 Feat: 사용자 맞춤 정보 수집 후 업데이트 API 구현
  costcook/src/main/java/com/costcook/config/WebMvcConfig.java
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
  costcook/src/main/java/com/costcook/controller/CommonRecipeController.java
  costcook/src/main/java/com/costcook/controller/UserController.java
  costcook/src/main/java/com/costcook/domain/request/UserUpdateRequest.java
  costcook/src/main/java/com/costcook/entity/Category.java
  costcook/src/main/java/com/costcook/entity/DislikedIngredient.java
  costcook/src/main/java/com/costcook/entity/DislikedIngredientId.java
  costcook/src/main/java/com/costcook/entity/PreferredIngredient.java
  costcook/src/main/java/com/costcook/entity/PreferredIngredientId.java
  costcook/src/main/java/com/costcook/entity/User.java
  costcook/src/main/java/com/costcook/repository/CategoryRepository.java
  costcook/src/main/java/com/costcook/repository/DislikedIngredientRepository.java
  costcook/src/main/java/com/costcook/repository/PreferredIngredientRepository.java
  costcook/src/main/java/com/costcook/service/FileUploadService.java
  costcook/src/main/java/com/costcook/service/UserService.java
  costcook/src/main/java/com/costcook/service/impl/FileUploadServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/UserServiceImpl.java
  costcook/src/main/java/com/costcook/util/FileUtils.java
  costcook/src/main/resources/data.sql
Labels: 기능 추가, 리팩토링, 백엔드

#20 Feat: 회원가입 및 로그인 응답 데이터 추가
  costcook/src/main/java/com/costcook/controller/UserController.java
  costcook/src/main/java/com/costcook/domain/response/SignUpOrLoginResponse.java
  costcook/src/main/java/com/costcook/entity/DislikedIngredient.java
  costcook/src/main/java/com/costcook/entity/PreferredIngredient.java
  costcook/src/main/java/com/costcook/service/impl/AuthServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/UserServiceImpl.java
Labels: 기능 추가, 백엔드

#22 Feat: 로그아웃 API 구현
  costcook/src/main/java/com/costcook/controller/AuthController.java
  costcook/src/main/java/com/costcook/domain/response/DefaultSuccessResponse.java
  costcook/src/main/java/com/costcook/service/AuthService.java
  costcook/src/main/java/com/costcook/service/impl/AuthServiceImpl.java
  costcook/src/main/java/com/costcook/util/TokenUtils.java
Labels: 기능 추가, 백엔드

#23 Feat: UserUpdateRequest의 필드를 선택 값으로 변경하고 preferences를 preferredIngred…
  costcook/src/main/java/com/costcook/domain/request/UserUpdateRequest.java
  costcook/src/main/java/com/costcook/service/impl/UserServiceImpl.java
Labels: 수정 요청, 백엔드

#28 Feat: 내 정보 조회 API 응답에 선호 재료 및 기피 재료 목록 추가
  costcook/src/main/java/com/costcook/controller/UserController.java
  costcook/src/main/java/com/costcook/domain/response/UserResponse.java
  costcook/src/main/java/com/costcook/entity/PreferredIngredient.java
  costcook/src/main/java/com/costcook/repository/DislikedIngredientRepository.java
  costcook/src/main/java/com/costcook/repository/PreferredIngredientRepository.java
  costcook/src/main/java/com/costcook/service/UserService.java
  costcook/src/main/java/com/costcook/service/impl/UserServiceImpl.java
Labels: 기능 추가, 백엔드

#32 Feat: 내 정보 조회 API 응답 데이터로 role 추가
  costcook/src/main/java/com/costcook/domain/response/UserResponse.java
Labels: 기능 추가, 백엔드

#30 리뷰 수정 추가
  .gitignore
  costcook/.gitignore
  costcook/src/main/java/com/costcook/controller/RecommendController.java
  costcook/src/main/java/com/costcook/controller/ReviewController.java
  costcook/src/main/java/com/costcook/domain/request/UpdateReviewRequest.java
  costcook/src/main/java/com/costcook/domain/response/UpdateReviewResponse.java
  costcook/src/main/java/com/costcook/exceptions/ForbiddenException.java
  costcook/src/main/java/com/costcook/exceptions/GlobalExceptionHandler.java
  costcook/src/main/java/com/costcook/exceptions/MessageExcepiton.java
  costcook/src/main/java/com/costcook/repository/ReviewRepository.java
  costcook/src/main/java/com/costcook/service/ReviewService.java
  costcook/src/main/java/com/costcook/service/impl/ReviewServiceImpl.java
Labels: 기능 추가, 백엔드

#35 Feat: 내 리뷰 목록 조회 API(페이징 포함) 구현
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
  costcook/src/main/java/com/costcook/controller/UserController.java
  costcook/src/main/java/com/costcook/domain/response/ReviewListResponse.java
  costcook/src/main/java/com/costcook/repository/ReviewRepository.java
  costcook/src/main/java/com/costcook/service/impl/ReviewServiceImpl.java
Labels: 기능 추가, 백엔드

#36 Feat: 레시피 관련 API 코드 통일화 및 리뷰 생성일 기준 정렬 기능 구현
  costcook/.gitignore
  costcook/src/main/java/com/costcook/controller/CommonRecipeController.java
  costcook/src/main/java/com/costcook/domain/response/RecipeDetailResponse.java
  costcook/src/main/java/com/costcook/domain/response/RecipeListResponse.java
  costcook/src/main/java/com/costcook/domain/response/RecipeResponse.java
  costcook/src/main/java/com/costcook/domain/response/ReviewListResponse.java
  costcook/src/main/java/com/costcook/entity/Recipe.java
  costcook/src/main/java/com/costcook/repository/RecipeRepository.java
  costcook/src/main/java/com/costcook/repository/ReviewRepository.java
  costcook/src/main/java/com/costcook/service/RecipeService.java
  costcook/src/main/java/com/costcook/service/ReviewService.java
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/ReviewServiceImpl.java
  costcook/src/main/resources/data.sql
Labels: 기능 추가, 리팩토링, 백엔드

#37 Feat: 레시피 검색 API 구현
  costcook/src/main/java/com/costcook/controller/CommonRecipeController.java
  costcook/src/main/java/com/costcook/domain/response/RecipeListResponse.java
  costcook/src/main/java/com/costcook/domain/response/RecipeResponse.java
  costcook/src/main/java/com/costcook/exceptions/GlobalExceptionHandler.java
  costcook/src/main/java/com/costcook/repository/RecipeRepository.java
  costcook/src/main/java/com/costcook/service/RecipeService.java
  costcook/src/main/java/com/costcook/service/ReviewService.java
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/ReviewServiceImpl.java
Labels: 기능 추가, 백엔드

#39 Feat: 내 리뷰 목록 조회 및 레시피 별 리뷰 목록 조회 API 응답 변경
  costcook/src/main/java/com/costcook/domain/response/ReviewResponse.java
Labels: 수정 요청, 백엔드

#41 Feat: 리뷰 조회 조건 수정 및 ReviewResponse DTO에 updated_at 필드 추가
  costcook/src/main/java/com/costcook/domain/response/ReviewResponse.java
  costcook/src/main/java/com/costcook/repository/ReviewRepository.java
  costcook/src/main/java/com/costcook/service/impl/ReviewServiceImpl.java
Labels: 버그, 백엔드
