Repository costcook-team/costcook-backend, pull requests merged in 2024-11, with the labels that each got.

#45 Feat: 즐겨찾기 목록 조회, 등록, 삭제 API 구현
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
  costcook/src/main/java/com/costcook/controller/CommonRecipeController.java
  costcook/src/main/java/com/costcook/controller/FavoriteController.java
  costcook/src/main/java/com/costcook/domain/request/CreateFavoritesRequest.java
  costcook/src/main/java/com/costcook/domain/response/CreateFavoritesResponse.java
  costcook/src/main/java/com/costcook/domain/response/DeleteFavoriteResponse.java
  costcook/src/main/java/com/costcook/domain/response/FavoriteListResponse.java
  costcook/src/main/java/com/costcook/domain/response/FavoriteRecipeResponse.java
  costcook/src/main/java/com/costcook/domain/response/FavoriteResponse.java
  costcook/src/main/java/com/costcook/domain/response/RecipeResponse.java
  costcook/src/main/java/com/costcook/entity/Favorite.java
  costcook/src/main/java/com/costcook/exceptions/AlreadyExistsException.java
  costcook/src/main/java/com/costcook/exceptions/GlobalExceptionHandler.java
  costcook/src/main/java/com/costcook/repository/FavoriteRepository.java
  costcook/src/main/java/com/costcook/repository/RecipeRepository.java
  costcook/src/main/java/com/costcook/service/FavoriteService.java
  costcook/src/main/java/com/costcook/service/RecipeService.java
  costcook/src/main/java/com/costcook/service/impl/FavoriteServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
Labels: 기능 추가, 백엔드

#47 Feat/weekly used budget
  costcook/build.gradle
  costcook/src/main/java/com/costcook/controller/CommonRecipeController.java
  costcook/src/main/java/com/costcook/controller/ReviewController.java
  costcook/src/main/java/com/costcook/controller/WeeklyBudgetController.java
  costcook/src/main/java/com/costcook/domain/response/WeeklyUsedBudgetResponse.java
  costcook/src/main/java/com/costcook/repository/RecipeRepository.java
  costcook/src/main/java/com/costcook/repository/RecommendedRecipeRepository.java
  costcook/src/main/java/com/costcook/service/ReviewService.java
  costcook/src/main/java/com/costcook/service/WeeklyBudgetService.java
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/ReviewServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/WeeklyBudgetServiceImpl.java
  costcook/src/main/resources/data.sql
Labels: 문서화

#48 Feat: 레시피 목록 조회 API 파라미터로 ids 추가 및 그에 따른 로직 구현
  costcook/src/main/java/com/costcook/controller/CommonRecipeController.java
  costcook/src/main/java/com/costcook/domain/response/RecipeListResponse.java
  costcook/src/main/java/com/costcook/service/RecipeService.java
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
Labels: 기능 추가, 백엔드

#51 Feat: recipeId 기반 내가 작성한 리뷰 조회 로직 구현 및 리뷰 작성 시 이미 해당 레시피 대상 리뷰 작성했을 시…
  costcook/src/main/java/com/costcook/controller/UserController.java
  costcook/src/main/java/com/costcook/repository/ReviewRepository.java
  costcook/src/main/java/com/costcook/service/ReviewService.java
  costcook/src/main/java/com/costcook/service/impl/FavoriteServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/ReviewServiceImpl.java
Labels: 수정 요청, 기능 추가, 백엔드

#52 Feat: 닉네임 중복여부 체크 API 구현
  costcook/src/main/java/com/costcook/CostcookApplication.java
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
  costcook/src/main/java/com/costcook/controller/UserController.java
  costcook/src/main/java/com/costcook/domain/response/NicknameCheckResponse.java
  costcook/src/main/java/com/costcook/exceptions/GlobalExceptionHandler.java
  costcook/src/main/java/com/costcook/repository/UserRepository.java
  costcook/src/main/java/com/costcook/service/UserService.java
  costcook/src/main/java/com/costcook/service/impl/UserServiceImpl.java
Labels: 기능 추가, 백엔드

#53 Fix: 내 리뷰 목록 조회 API 및 레시피 상세정보 조회 API 변경
  costcook/src/main/java/com/costcook/domain/response/RecipeDetailResponse.java
  costcook/src/main/java/com/costcook/repository/ReviewRepository.java
Labels: 수정 요청, 백엔드

#54 getRecipesByBudget 계산 변경
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
Labels: 수정 요청, 백엔드

#55 Feat: 로그인 시 비회원이 저장한 즐겨찾기, 예산, 레시피 추천 목록 데이터 존재하는 경우 저장 로직 추가
  costcook/src/main/java/com/costcook/controller/RecommendController.java
  costcook/src/main/java/com/costcook/domain/request/CreateFavoritesRequest.java
  costcook/src/main/java/com/costcook/domain/request/DefaultRecommendedRecipe.java
  costcook/src/main/java/com/costcook/domain/request/SignUpOrLoginRequest.java
  costcook/src/main/java/com/costcook/service/RecipeService.java
  costcook/src/main/java/com/costcook/service/impl/AuthServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/RecipeServiceImpl.java
  costcook/src/main/java/com/costcook/service/impl/WeeklyBudgetServiceImpl.java
Labels: 기능 추가, 백엔드

#59 hotfix: 배포를 위한 CORS 설정 변경
  costcook/src/main/java/com/costcook/config/WebMvcConfig.java
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
  costcook/src/main/resources/data.sql
Labels: 버그, 백엔드

#60 hotfix: 이미지 접근 경로 변경
  costcook/src/main/java/com/costcook/config/WebSecurityConfig.java
Labels: 버그, 백엔드

#61 Fix: 이미지 리소스 캐싱 처리
  costcook/src/main/java/com/costcook/config/WebMvcConfig.java
Labels: 성능 개선, 백엔드
